modLoader = "javafml"
loaderVersion="[40,)"
license="None"
logoFile="banner.png"

[[mods]]
modId="watching"
version="1.9.3"
displayName="From The Fog"
credits="§8Created by §5☆Lunar Eclipse Studios☆"
displayURL="https://lunareclipse.studio/creations/from-the-fog"
issueTrackerURL="https://github.com/LunarEclipseStudios/From-The-Fog/issues"
authors="Bret06"
description='''Enter a world of fear and mystery with From The Fog, a Minecraft mod that brings the legendary Herobrine to life in a spooky and immersive way true to the legend.'''

[[dependencies.watching]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.3, 1.20.4]"
    ordering="NONE"
    side="BOTH"